version: '3'
services:
  app:
    build: ./webapp/
    env_file:
      - ./webapp/.env
    ports:
      - "3000:80"
  server:
    build: ./service
    env_file:
      - ./service/.env
    ports:
      - "5200:5200"